from ament_index_python.packages import PackageNotFoundError

from .actions import ProcessParamsFile, SetGlobalNamespace, SetRobotNamespace, SetRobotPrefix
from .helpers import (
    DEFAULT_LOGGING_OPTIONS,
    DEFAULT_NODE_OPTIONS,
    LOGGING_OPTIONS_DESC,
    NODE_OPTIONS_DESC,
    REMAPPINGS_DESC,
    FileResolutionError,
    InvalidFileUriPatternError,
    NullFilePathError,
    compute_global_namespace,
    compute_robot_namespace,
    compute_robot_prefix,
    default_node_logging_options_json_str,
    default_node_options_json_str,
    default_node_remappings_json_str,
    flatten_namespace,
    get_parameters,
    is_valid_name,
    read_yaml_file,
    render_params_file,
    replace_separator_in_namespace,
    resolve_file,
    resolve_name,
    resolve_node_launch_configs,
    to_log_info_actions,
    to_prefix,
)
from .version import __version__

__all__ = [
    'DEFAULT_LOGGING_OPTIONS',
    'DEFAULT_NODE_OPTIONS',
    'NullFilePathError',
    'FileResolutionError',
    'InvalidFileUriPatternError',
    'LOGGING_OPTIONS_DESC',
    'NODE_OPTIONS_DESC',
    'PackageNotFoundError',
    'ProcessParamsFile',
    'REMAPPINGS_DESC',
    'SetGlobalNamespace',
    'SetRobotNamespace',
    'SetRobotPrefix',
    'compute_global_namespace',
    'compute_robot_namespace',
    'compute_robot_prefix',
    'default_node_logging_options_json_str',
    'default_node_options_json_str',
    'default_node_remappings_json_str',
    'flatten_namespace',
    'get_parameters',
    'is_valid_name',
    'read_yaml_file',
    'replace_separator_in_namespace',
    'render_params_file',
    'resolve_node_launch_configs',
    'resolve_file',
    'resolve_name',
    'to_prefix',
    'to_log_info_actions',
    '__version__',
]
